### ISSUE TITLE
country in address structures

### ISSUE THREAD

**Issue by 1on** [jetverzendt/snelweg#1]
Hello, can you help me - how should i work with countries? ISO 639-1 encodes language but not country. Many countries has same main languages so, for example, how should i create delivery to USA and UK? Or maybe this countries are not available to work with? If i`m right cant you tell please for what countries i can create deliveries through KeenDelivery API?

And one more question - for product Inleveren Parcelshop (DHL) (DHLPacelshop) i should send parcel_shop_id. I can get it from Parcel Shop finder with "products" => "DHL" ?

**Comment by jacob-v-dam** [comment]
You are right, it should be ISO 3166-1. I will fix this in the documentation.

**Comment by 1on** [comment]
Nice, that`s what i need. Thank you!
